backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "public/assets/images"
public_folder: "/assets/images"
collection:
  - name: "Post"
    label: "post"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
